# Generated by Django 5.1.2 on 2024-10-30 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(default='service name', max_length=100)),
                ('service_icon', models.CharField(default='fas fa-file-alt', max_length=100)),
                ('service_tagline', models.ImageField(default='https://emifreecar.com/images-new/offcer-coming-soon.jpg', upload_to='services_tagline')),
                ('service_importance', models.TextField(default='Importance of Service')),
                ('service_mission', models.TextField(default='Mission')),
                ('service_valueproposition', models.ImageField(default='https://emifreecar.com/images-new/offcer-coming-soon.jpg', upload_to='services_valueproposition')),
                ('service_mainheading', models.ImageField(default='https://emifreecar.com/images-new/offcer-coming-soon.jpg', upload_to='services_mainheading')),
                ('service_introheading', models.CharField(default='Intro Heading', max_length=500)),
                ('service_intro', models.TextField(default='Introduction')),
                ('service_whatweoffer_heading', models.CharField(default='What we offer (Heading)', max_length=500)),
                ('service_whatweoffer_desc', models.TextField(default='What we offer (desc)')),
                ('service_whychoose_heading', models.CharField(default='why choose (heading)', max_length=500)),
                ('service_whychoose_desc', models.TextField(default='why choose (desc)')),
                ('service_getstartedtoday_heading', models.CharField(default='Get started today (heading)', max_length=100)),
                ('service_getstartedtoday_desc', models.TextField(default='Get started Today (Desc)')),
                ('service_quote', models.ImageField(default='https://emifreecar.com/images-new/offcer-coming-soon.jpg', upload_to='services_quote')),
                ('service_thankyou', models.TextField(default='Thank You Message')),
                ('service_img1', models.ImageField(default='https://emifreecar.com/images-new/offcer-coming-soon.jpg', upload_to='services')),
                ('service_img2', models.ImageField(default='https://emifreecar.com/images-new/offcer-coming-soon.jpg', upload_to='services')),
                ('service_img3', models.ImageField(default='https://emifreecar.com/images-new/offcer-coming-soon.jpg', upload_to='services')),
                ('pricing_junior', models.CharField(default='Junior', max_length=100)),
                ('pricing_juniorprice', models.IntegerField(default='100')),
                ('pricing_mid', models.CharField(default='Mid', max_length=100)),
                ('pricing_no_year', models.CharField(default='No. of years', max_length=50)),
                ('pricing_midprice', models.IntegerField(default='100')),
                ('pricing_senior', models.CharField(default='senior', max_length=100)),
                ('pricing_year', models.CharField(default='no of years', max_length=50)),
                ('pricing_seniorprice', models.IntegerField(default='100')),
                ('pricing_top', models.CharField(default='Top', max_length=100)),
                ('pricing_n_years', models.CharField(default='no of years', max_length=50)),
                ('pricing_topprice', models.IntegerField(default='100')),
            ],
        ),
    ]
