# Generated by Django 5.1.2 on 2024-11-05 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xtracareers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='pricings_year',
            field=models.CharField(default='no. of years', max_length=50),
        ),
    ]
