# Generated by Django 5.1.2 on 2024-11-19 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xtracareers', '0002_services_pricings_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Customer Name', max_length=500)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=15)),
                ('experience_level', models.CharField(choices=[('0-5', '0 to 5 years'), ('6-10', '6 to 10 years'), ('11-15', '11 to 15 years'), ('15+', '15 years +')], max_length=10)),
                ('selected_services', models.JSONField()),
            ],
        ),
    ]
