# Generated by Django 5.1.2 on 2024-11-28 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xtracareers', '0006_alter_payment_selected_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='selected_services',
            field=models.JSONField(),
        ),
    ]
