# Generated by Django 5.1.2 on 2024-11-29 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xtracareers', '0007_alter_payment_selected_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='candidate_cv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv_name', models.CharField(default='Name', max_length=500)),
                ('cv_contact', models.IntegerField(default='1234567890')),
                ('cv_email', models.EmailField(default='email@gmail.com', max_length=254)),
                ('key_skills', models.TextField(default='key skills')),
                ('cv_total_experience', models.IntegerField(blank=True, default='1', null=True)),
                ('cv_undergraduate', models.TextField(default='undergraduate')),
                ('cv_postgraduate', models.TextField(default='postgraduate')),
                ('cv_certifications', models.TextField(blank=True)),
                ('veteran_status', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('resumes', models.FileField(upload_to='resumes/')),
            ],
        ),
    ]
