# Generated by Django 5.1.2 on 2024-12-03 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xtracareers', '0009_faqs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='pricing_juniorprice',
            field=models.CharField(default='100', max_length=200),
        ),
        migrations.AlterField(
            model_name='services',
            name='pricing_midprice',
            field=models.CharField(default='100', max_length=200),
        ),
        migrations.AlterField(
            model_name='services',
            name='pricing_seniorprice',
            field=models.CharField(default='100', max_length=200),
        ),
        migrations.AlterField(
            model_name='services',
            name='pricing_topprice',
            field=models.CharField(default='100', max_length=200),
        ),
    ]
