# Generated by Django 5.1.2 on 2024-12-07 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xtracareers', '0010_alter_services_pricing_juniorprice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='invoice_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
