# Generated by Django 5.1.2 on 2024-12-09 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xtracareers', '0012_payment_invoice_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='invoice_status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
