# Generated by Django 5.1.2 on 2024-12-10 09:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xtracareers', '0013_payment_invoice_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='invoice_url',
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
