# Generated by Django 5.1.2 on 2024-12-17 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xtracareers', '0015_payment_invoice_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='further_detail_mail',
            field=models.TextField(default='Further Detail of Services for Mail'),
        ),
    ]
